### ISSUE TITLE
OpenTabletop Default Asset Pack TODO

### ISSUE THREAD

**Issue by drwhut** [drwhut/open-tabletop#28]
# Preface

The game allows for the importing of custom assets via *asset packs*, which contain things like textures and scenes that are then converted to in-game pieces. More information about assets can be found [here](https://github.com/drwhut/open-tabletop/tree/master/assets).

The game comes with the [default asset pack](https://github.com/drwhut/open-tabletop/tree/master/assets/OpenTabletop), which should contain assets for the most common board game pieces used by players. This issue will serve as a TODO list for adding these pieces to the default pack.

Note that the default pack will only contain pieces belonging to **public-domain board games**! For reference, you can find a list of the most popular public-domain games in [this blog post](https://boardgamegeek.com/blogpost/95124/public-domain-games).

# Submitting Assets

If you have either made or have found assets that you think should be in the default pack, then feel free to [open an issue](https://github.com/drwhut/open-tabletop/issues/new/choose) with the asset submission template! Note that we will only accept assets with an open license, e.g. the [CC BY-SA 4.0 license](https://creativecommons.org/licenses/by-sa/4.0/). For more information about contributing to the project in general, see [the contributing guide](https://github.com/drwhut/open-tabletop/blob/master/CONTRIBUTING.md).

# TODO

## Perudo / Liar's Dice

- [ ] Cups (see #27)
- [ ] Coloured D6

## Crokinole

**NOTE:** This game requires flicking pieces to be implemented.

- [ ] Crokinole board
- [ ] Generic cylinder pieces

## Chess

- [ ] Chess board
- [ ] Chess pieces

## Poker

- [x] Playing cards
- [x] Poker chips

## Cribbage

- [x] Playing cards
- [ ] Cribbage board
- [ ] Cribbage pegs

## Yahtzee

**NOTE:** This game requires notepads to be implemented.

- [ ] Cups (see #27)
- [ ] D6
- [ ] Yahtzee scoring notepads

## Backgammon

- [ ] Backgammon board
- [ ] Generic cylinder pieces
- [ ] D6
- [ ] Cups (see #27)
- [ ] Doubling D6

## Go

- [ ] Go board
- [ ] Black and white stones

## Werewolf

- [ ] Villager card(s)
- [ ] Werewolf card(s)
- [ ] Seer card
- [ ] Extra role cards

## Connect Four

**NOTE:** This game requires animatable objects to be implemented.

- [ ] Connect Four grid
- [ ] Generic cylinder pieces

## Dominoes

- [ ] ... Dominoes

## Kalah

- [ ] Kalah board
- [ ] Stones

## Othello

- [ ] Othello board
- [ ] Generic cylinder pieces

## Mahjong

- [ ] Mahjong tiles

## Checkers

- [ ] Chess/Checkers board
- [ ] Generic cylinder pieces

## Memory

- [ ] Picture cards

## Hearts

- [x] Playing cards

## Euchre

- [x] Playing cards

## Eat Poop You Cat

**NOTE:** This is an amazing name for a board game, and it also requires notepads to be implemented.

## Pachisi

- [ ] Pachisi board
- [ ] Pachisi pawns
- [ ] D6

## Rummy

- [x] Playing cards

## Oh Hell!

- [x] Playing cards

## Go Fish

- [x] Playing cards

## Chinese Checkers

- [ ] Chinese Checkers board
- [ ] Chinese Checkers pieces

## Snakes and Ladders

- [ ] Snakes and Ladders board
- [ ] Pawns
- [ ] D6

## Bridge

- [x] Playing cards

## Spades

- [x] Playing cards

**Comment by SeanKuehl** [comment]
Hey drwhut, I might try and add some picture cards for the game "memory", I was wondering what kind of images you would be looking for and what general size the cards should be ie. "playing card size" or larger.

**Comment by drwhut** [comment]
Hey! The only things I'm looking for when it comes to the images are just semantics, like:

* The images must be under an open license.
* The images must have a decent resolution (so you can't see the pixels when zooming in in-game).
* The images look cool (although this is subjective :smile:).

In terms of the sizes of the cards, they can be configured regardless of the resolution of the images themselves, so I wouldn't worry too much about the size of the cards as long as they're a sensible size I'm happy!

**Comment by SeanKuehl** [comment]
Here are two things I was looking at to use for the memory card images. Both are CC0 so license shouldn't be a problem.

first link(birds): https://opengameart.org/content/update-animated-birds-character-sheet

second link (characters): https://opengameart.org/content/platformer-art-deluxe
note for the second: I would only be using the characters(player characters/enemies) and maybe some of the symbols(like diamonds, keys, and torches)

**Comment by SeanKuehl** [comment]
I have found new images that meet all criteria and have been tested out in game. I'm wondering how to add them into the default asset pack "cards" folder. In the documentation I read that there is a way to apply properties to everything in a subfolder or one individual item, is there another way? To be more specific, could I apply one description, back face etc. to the playing cards and another set of those things to my memory cards without having to specify all or some cards individually?

**Comment by drwhut** [comment]
As well as applying properties to all cards and specific cards, you can apply properties to cards whose names begin with a certain string, for example, if all the memory cards are called `Memory <...>.png`, then you can apply properties to all of the memory cards with:

```ini
[Memory*]
back_face = "memory_back.png"
```

**Comment by SeanKuehl** [comment]
Thanks, that is a huge help. So now am I ready to make a pull request adding my Memory game assets into the standard asset pack?

**Comment by drwhut** [comment]
Actually, since it's mostly going to be images, it might be easier to send the folder as a .zip in this thread (by drag and dropping the file into the comment box). Only because git doesn't store binary files like images very efficiently.

**Comment by SeanKuehl** [comment]
[memory game assets.zip](https://github.com/drwhut/tabletop-club/files/6680478/memory.game.assets.zip)
here you go.

**Comment by drwhut** [comment]
The images are fine, but would it be possible to make it so that the images aren't stretched? Maybe have the images be cropped on top of a background image, for example?

**Comment by SeanKuehl** [comment]
Instead of getting the original images in the largest size and shrinking them down to a specific resolution, which is how I stretched them I did something different this time. I downloaded the smaller versions of the images which aren't stretched. Check out the new versions and see what you think:
[Memory Game Images.zip](https://github.com/drwhut/tabletop-club/files/6686160/Memory.Game.Images.zip)

**Comment by drwhut** [comment]
There's still the problem that even though the images in the file system aren't stretched, the game will stretch the images to fit the configured card size:

![2021-6-21-15-48-12](https://user-images.githubusercontent.com/13645454/122782087-56f27100-d2a8-11eb-985c-426915aced88.png)

**Comment by SeanKuehl** [comment]
All the images are slightly different sizes, at least some of them might appear stretched on any card size, would it be ok if I made the card size bigger until there was only a little stretching or do you think it would still be bad?

**Comment by drwhut** [comment]
Eh, I would probably either crop the image, or if cropping isn't possible, put the image on top of a background image that is the right size.

**Comment by 20kdc** [comment]
regarding the othello board: the chess board should work fine for othello if I correctly recall the game rules, unless you want something specifically adapted to it somehow?

**Comment by drwhut** [comment]
Ah, you're right! From what I looked at online, usually, Othello boards are green, but it's still fundamentally just an 8x8 board. Thanks for the spot!

**Comment by SeanKuehl** [comment]
Drwhut, how were the dimensions figured out for the playing cards? I think I can crop all the images to a common size, but I'd still need to change the size of the cards in game to avoid stretching.

**Comment by drwhut** [comment]
The playing card dimensions were based on a standard playing card size. The cards don't necessarily need to be the same size as the playing cards, but as long as they're all the same size (such that they can stack).

**Comment by SeanKuehl** [comment]
I have made all the images the same size. 
[Memory card assets.zip](https://github.com/drwhut/tabletop-club/files/6704753/Memory.card.assets.zip)

**Comment by SeanKuehl** [comment]
Just checking in about my latest memory card submission. Let me know if the issues are resolved or whether it needs more refactoring.

**Comment by drwhut** [comment]
Sorry for the late reply! Just moved out of university, so I should be a lot more active in the coming weeks.

The cropping method seems to work fine! My only issue now is the cards themselves. This is just my opinion, but I personally think the cards should maybe be a bit more 'cartoony', rather than realistic. Plus, we should probably try and find more animals/objects to put in as well. What do you think?

**Comment by SeanKuehl** [comment]
Yeah, more 'cartoony' cards would better fit the overall 'cozy' feeling you're going for for the game. I was thinking that 12 cards was a healthy amount because if you use all of them in one game you would have a 24 card game of memory, but if you want I can expand to more cards. It might take me some time to find all new images.

**Comment by SeanKuehl** [comment]
I found some cartoony images under the CCO license(https://opengameart.org/content/cartoon-enemies). I was wondering what you thought of them. Here's what they look like all the same size and the same size as my previously submitted images: 
[images.zip](https://github.com/drwhut/tabletop-club/files/7023652/images.zip)

**Comment by drwhut** [comment]
I like the images, but I feel that they're a bit too... "whacky"? I think if we're going to add images for Memory, they should be as "straightforward" as possible, if that makes any sense. There are some images in that set that would suit it well, for example the ghost or the slimes - but most of the creatures in that set are a bit too out there, in my opinion.

**Comment by SeanKuehl** [comment]
Yeah, some of the images are a little out-there for a memory game. I sorted out some images I thought were too "whacky" and would like to see what you think of the remaining images, some more might need to be taken out. 
[newImages.zip](https://github.com/drwhut/tabletop-club/files/7025542/newImages.zip)

**Comment by SeanKuehl** [comment]
I made some images for the Werewolf game. I've made a Werewolf, Villager, and Seer card. Let me know what you think, if these cards are good I can make cards for the extra roles as well.

**Comment by drwhut** [comment]
Apologies for the long delay in my response - I just wanted to mention that since I am currently preparing to release the game, I have decided to hold off on adding any more assets to the default pack until after the initial release (unless there's a lot of demand to add something, in which case I'll make an exception :wink: )

**Comment by drawnto** [comment]
The link [default asset pack](https://github.com/drwhut/open-tabletop/tree/master/assets/OpenTabletop), in the first post bit rotted.
